### ISSUE TITLE
Is something wrong with the cell?

### ISSUE THREAD

**Issue by liusiye** [dennybritz/chatbot-retrieval#1]
hi,denny,shoul we use
 "cell = tf.nn.rnn_cell.BasicLSTMCell(LSTM_CELL_SIZE,input_size=EMBEDDING_SIZE)" instead of  "cell = tf.nn.rnn_cell.BasicLSTMCell(LSTM_CELL_SIZE)"?

**Comment by dennybritz** [comment]
Why do you think so? The dimensions seem right to me, otherwise TF would throw an error.
