### ISSUE TITLE
incompatible parameter initialization

### ISSUE THREAD

**Issue by amirj** [dennybritz/chatbot-retrieval#13]
As mentioned in the original paper:

> The RNN architecture is set to 1 hidden layer with 50 neurons. The W_h matrix is initialized using **orthogonal weights [23]**, while W_x is initialized using a **uniform distribution with values between -0.01 and 0.01**. We use Adam as our optimizer [15], with gradients clipped to 10. **We found that weight initialization as well as the choice of optimizer were critical for training the RNNs**.

In the implementation, [W_x is initialized uniformly between -0.25 and 0.25](https://github.com/dennybritz/chatbot-retrieval/blob/master/models/dual_encoder.py#L15). Also, [W_h is initialized using tf.truncated_normal_initializer](https://github.com/dennybritz/chatbot-retrieval/blob/master/models/dual_encoder.py#L62).

Initialization may have a little effect on the performance and get more compatible results.

**Comment by dennybritz** [comment]
Yeah, that's true. I remember playing around with the initialization of that but I don't remember what the conclusion was. I think it didn't have much of an effect.

 Thanks for pointing it out though, you're right that this is different from the paper.
