### ISSUE TITLE
Cannot Evaluating the model using udc_test.py

### ISSUE THREAD

**Issue by tviangte** [dennybritz/chatbot-retrieval#14]
Got the following errors. Should I have to change anything in udc_test.py?

Traceback (most recent call last):
File
"udc_test.py", line 39, in <module>
estimator.evaluate(input_fn=input_fn_test, steps=None,
metrics=eval_metrics)
File
"/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py",
line 356, in evaluate
name=name)
File
"/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/estimators/estimator.py",
line 641, in _evaluate_model
max_steps=steps)
File
"/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py",
line 773, in evaluate
_write_summary_results(output_dir, eval_results, current_global_step)
File
"/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py",
line 613, in _write_summary_results
_eval_results_to_str(eval_results))
File
"/Library/Python/2.7/site-packages/tensorflow/contrib/learn/python/learn/graph_actions.py",
line 607, in _eval_results_to_str
return ', '.join('%s = %s' % (k, v) for k, v in eval_results.items())
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by dennybritz** [comment]
This code only supports Python 3 right now.
