### ISSUE TITLE
Get an error - python udc_train.py

### ISSUE THREAD

**Issue by zhoucrawl** [dennybritz/chatbot-retrieval#18]
Try to run the program from Ubuntu15.10 with Python3.4 and tensorflow-0.9.0.I hope you have time to answer, thank you

![ubuntu-danji-2016-08-29-22-22-59](https://cloud.githubusercontent.com/assets/19216554/18054832/15a426e6-6e38-11e6-99d1-d9dc645d12b1.png)

![ubuntu-danji-2016-08-29-22-24-25](https://cloud.githubusercontent.com/assets/19216554/18054840/200f34ae-6e38-11e6-82c0-be998fee7813.png)

**Comment by dennybritz** [comment]
It says file not found, so your training data file isn't there.

**Comment by zhoucrawl** [comment]
Thank you very much！
Recent studies chatbot,feeling too hard.
