### ISSUE TITLE
'moving_average_decay' keyword argument

### ISSUE THREAD

**Issue by DE-TungHoang** [dennybritz/chatbot-retrieval#24]
I got the following error when running your code in Tensorflow:

TypeError: optimize_loss() got an unexpected keyword argument 'moving_average_decay'

The error code is:
def create_train_op(loss, hparams):
  train_op = tf.contrib.layers.optimize_loss(
      loss=loss,
      global_step=tf.contrib.framework.get_global_step(),
      learning_rate=hparams.learning_rate,
      clip_gradients=10.0,
      moving_average_decay=None, #### error here
      optimizer=hparams.optimizer)
  return train_op

I searched for the doc of "tf.contrib.layers.optimize_loss" but could not find the keyword. Can you please fix this?

**Comment by dennybritz** [comment]
Seems like they changed the API for that function in the new versions.
