### ISSUE TITLE
Getting error while running the training script.

### ISSUE THREAD

**Issue by jugador** [dennybritz/chatbot-retrieval#30]
Hi,
I am a newbie and was going through your amazing tutorial on chatbots. While training the model with udc_train.py script I am getting the error:
`InvalidArgumentError (see above for traceback): Incompatible shapes: [80,1] vs. [160,1]
	 [[Node: prediction/logistic_loss/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](prediction/Squeeze, prediction/ToFloat)]]`

 Please recommend what steps I can take to train the models properly.

**Comment by Sangheli** [comment]
#15 has info to fix it

**Comment by dennybritz** [comment]
Yep, thanks!

**Comment by rguptabinary** [comment]
After following #15 and changing the values now getting errors in udc_test.py script.
`InvalidArgumentError (see above for traceback): Incompatible shapes: [80,1] vs. [160,1]
	 [[Node: prediction/logistic_loss/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](prediction/Squeeze, prediction/ToFloat)]]
`

**Comment by guilhermevarela** [comment]
@rguptabinary I'm having the same issue over here. Any fixes as of now?

**Comment by pengcao** [comment]
@rguptabinary I'm having the same issue over here. Any fixes as of now?
