### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by binaykumarsahoo** [dennybritz/chatbot-retrieval#60]
Traceback (most recent call last):
  File "udc_predict.py", line 58, in <module>
    print("{}: {:g}".format(r, prob[0, 0]))
TypeError: 'generator' object is not subscriptable

**Comment by SergeyLobanov** [comment]
I have same error running it with different versions of python and tensorflow. 
Does somebody know how to fix it or any ideas?

**Comment by ThanhChinhBK** [comment]
I try this and it worked :dancing_men: 
`print("{}: {:g}".format(r, next(prob)[0]))
`
