### ISSUE TITLE
InvalidArgumentError

### ISSUE THREAD

**Issue by yanqiangmiffy** [dennybritz/chatbot-retrieval#66]
InvalidArgumentError (see above for traceback): indices[58,29] = 107043 is not in [0, 91620)
	 [[Node: embed_context = GatherV2[Taxis=DT_INT32, Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@OptimizeLoss/train/update_word_embeddings/AssignSub"], _device="/job:localhost/replica:0/task:0/device:CPU:0"](word_embeddings/read, read_batch_features_train/fifo_queue_Dequeue, embed_context/axis)]]

**Comment by yanqiangmiffy** [comment]
需要更改vacab_size

**Comment by pengcao** [comment]
改成多少合适？  Thanks!
