### ISSUE TITLE
Python 2.7.6 hit "unsupported pickle protocol: 3"

### ISSUE THREAD

**Issue by realentertain** [dennybritz/chatbot-retrieval#8]
This might be a tensorflow issue. 
**xxx$ python udc_predict.py --model_dir=./runs/1468290997/**
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "udc_predict.py", line 27, in <module>
    FLAGS.vocab_processor_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/preprocessing/text.py", line 228, in restore
    return pickle.loads(f.read())
ValueError: unsupported pickle protocol: 3

**Looks like the default pickle protocol for tensorflow is 3 which is not supported by Python2.x.**
**From Python cli, I saw the highest protocol supported is 2.**
xx$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> print pickle.HIGHEST_PROTOCOL
2
>>> import cPickle
>>> print cPickle.HIGHEST_PROTOCOL
2

**Comment by dennybritz** [comment]
I didn't test the code with Python 2, right now it's Python 3 only. But yeah, this seems like a Tensorflow issue. Make sure you have the latest versions of everything (including pip) and maybe ask in the Tensorflow forums.
