### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Estimator'

### ISSUE THREAD

**Issue by loveJasmine** [dennybritz/chatbot-retrieval#9]
envy@ub1404:/media/envy/data1t/os_prj/github/chatbot-retrieval$ python udc_train.py
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "udc_train.py", line 70, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "udc_train.py", line 37, in main
    estimator = tf.contrib.learn.Estimator(
AttributeError: 'module' object has no attribute 'Estimator'
envy@ub1404:/media/envy/data1t/os_prj/github/chatbot-retrieval$

**Comment by dennybritz** [comment]
Update Tensorflow.
